name: bookreader
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  http: ^1.2.2
  image_picker: ^1.1.2
  provider: ^6.1.2
  path: ^1.9.0
  just_audio:
  path_provider: ^2.1.5
  mime: ^2.0.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  connectivity_plus: ^6.1.0
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  syncfusion_flutter_pdfviewer: ^28.1.33
  syncfusion_flutter_core: ^28.1.33
  encrypt: ^5.0.3
  flutter_launcher_icons: ^0.11.0
  device_info_plus: ^11.3.0
  permission_handler: ^11.3.1
  audio_session: ^0.1.21
  flutter_slidable: ^4.0.0
  archive: ^3.6.1
  # flutter_quill: ^10.8.5
  video_player: ^2.9.2
  docx_viewer: ^0.2.1
  # flutter_epub_viewer: ^1.2.0
  app_links: ^6.3.3
  no_screenshot: ^0.3.1
  flutter_spinkit: ^5.2.1
  go_router: ^14.6.3
  animated_dropdown_search_codespark: ^2.0.2
  file_picker: ^8.1.7
  # vocsy_epub_viewer:
  cosmos_epub: ^0.0.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: "assets/icon/icon.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
