name: book_mobile
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  http: ^1.2.2
  image_picker: ^1.1.2
  provider: ^6.1.2
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2
  path: ^1.9.0
  flutter_pdfview: ^1.3.4
  path_provider: ^2.1.5
  mime: ^2.0.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  connectivity_plus: ^6.1.0
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  syncfusion_flutter_pdfviewer: ^28.1.33
  syncfusion_flutter_core: ^28.1.33
  encrypt: ^5.0.3
  # flutter_launcher_icons: ^0.14.1
  font_awesome_flutter: ^10.8.0
  device_info_plus: ^10.1.2
  permission_handler: ^11.3.1
  wolt_modal_sheet: ^0.10.0
  just_audio: ^0.9.42
  audio_session: ^0.1.21
  rxdart: ^0.28.0
  flutter_slidable: ^3.1.2
  docx_template: ^0.4.0
  flutter_widget_from_html: ^0.15.3
  archive: ^3.6.1
  webview_flutter: ^4.10.0
  flutter_quill: ^10.8.5
  epubx: ^4.0.0
  video_player: ^2.9.2
  docx_viewer: ^0.2.1
  flutter_epub_viewer: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/icons/ic_launcher.png"
#   adaptive_icon_background: "#FF6A331E"
#   adaptive_icon_foreground: "assets/icons/ic_launcher.png"
#   remove_alpha_ios: true

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
